[package]
name = "astrolabe-bin"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[[bin]]
name = "astrolabe"
path = "src/main.rs"

[features]

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
rand_xorshift = "0.3.0"
rand = "0.8"
serde_json = "1.0.135"
parse_int = "0.6.0"

[target.'cfg(not(any(target_arch = "x86", target_arch = "i686")))'.dependencies]
astrolabe = { path = "../lib", version = "0.1", features = [
  "f64",
] } # 64 bit library

[target.'cfg(any(target_arch = "x86", target_arch = "i686"))'.dependencies]
# 32 bit library
astrolabe = { path = "../lib", version = "0.1", default-features = false }

[build-dependencies]
clap_mangen = "0.2.26"
clap = { version = "4.5.26", features = ["derive"] }
clap_complete = "4.5.42"
