[package]
name = "astrolabe-bin"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
astrolabe = { path = "../lib", version = "0.1" }
rand_xorshift = "0.3.0"
rand = "0.8"
serde_json = "1.0.135"
parse_int = "0.6.0"
