coverage:
  status:
    project:
      binary:
        informational: true
        target: 50
        threshold: 10
        paths:
          - bin

      library:
        informational: false
        target: 50
        threshold: 10
        paths:
          - lib

      wasm:
        # Making informational until `wasm-pack test` can be used to generate coverage
        informational: true
        target: 50
        threshold: 10
        paths:
          - wasm

    patch:
      default:
        informational: true
        target: 50
        threshold: 10
