name: Clippy

on:
  push:
    branches:
      - dev
      - master
      - "release-candidate/**"
  pull_request:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  clippy_regular_check:
    strategy:
      matrix:
        arguments: [--feature f64, --no-default-features]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets ${{ matrix.arguments }}
      - name: Run Clippy (Pedantic)
        run: cargo clippy --all-targets ${{ matrix.arguments }} -- -D cippy::pedantic
        continue-on-error: true
