name: Code Coverage

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]
    paths:
      - lib/**/*.rs
      - bin/**/*.rs

env:
  CARGO_TERM_COLOR: always

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Generate Test Coverage
        run: |
          cargo tarpaulin --follow-exec --engine llvm --verbose --all-features --workspace --timeout 120 --out xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          # Specify whether the Codecov output should be verbose
          verbose: true
          fail_ci_if_error: false
