name: Release Binaries

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

permissions:
  contents: write

jobs:
  wasm-and-completions:
    name: Build additional artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build --target web --release -d ../web/pkg wasm && tar -cvzf wasm.tar.gz web/pkg
      - run: cargo build --bin astrolabe
      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body_path: CHANGELOG.md
          # Add completion files, wasm tar, and the README
          files: |
            wasm.tar.gz
            README.md

  build-binaries:
    name: Build Release Binaries - ${{ matrix.platform.os-name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            extra-files: |
              completions/_astrolabe
              completions/astrolabe.bash
              completions/astrolabe.elv
              completions/astrolabe.fish
              completions/astrolabe.1

          - os-name: Linux-i686
            runs-on: ubuntu-20.04
            target: i686-unknown-linux-musl
            extra-files: |
              completions/_astrolabe
              completions/astrolabe.bash
              completions/astrolabe.elv
              completions/astrolabe.fish
              completions/astrolabe.1

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl
            extra-files: |
              completions/_astrolabe
              completions/astrolabe.bash
              completions/astrolabe.elv
              completions/astrolabe.fish
              completions/astrolabe.1

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            extra-files: |
              completions/_astrolabe.ps1

          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            extra-files: |
              completions/_astrolabe.ps1

          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            extra-files: |
              completions/_astrolabe
              completions/astrolabe.bash
              completions/astrolabe.elv
              completions/astrolabe.fish
              completions/astrolabe.1

          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
            extra-files: |
              completions/_astrolabe
              completions/astrolabe.bash
              completions/astrolabe.elv
              completions/astrolabe.fish
              completions/astrolabe.1

          - os-name: macOS-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin
            extra-files: |
              completions/_astrolabe
              completions/astrolabe.bash
              completions/astrolabe.elv
              completions/astrolabe.fish
              completions/astrolabe.1

    runs-on: ${{ matrix.platform.runs-on }}
    needs: [wasm-and-completions]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary for ${{ matrix.platform.os-name }}
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: "--bin astrolabe --release --locked"
          strip: true
      - name: Get completions
        run: |
          mkdir completions
          cp target/${{ matrix.platform.target }}/release/build/astrolabe-bin-*/out/* completions/
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0.0.4
        with:
          executable-name: astrolabe
          target: ${{ matrix.platform.target }}
          archive-name: ${{ matrix.platform.os-name }}
          # Changelog and readme provided by wasm-and-completions
          changes-file: CHANGELOG.md
          extra-files: ${{ matrix.platform.extra-files }}
