name: Release Binaries

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  CROSS_CONTAINER_IN_CONTAINER: true

jobs:
  wasm-and-completions:
    name: Build additional artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build --target web --release -d ../web/pkg wasm && tar -cvzf wasm.tar.gz web/pkg
      - run: cargo build --bin astrolabe
      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body_path: CHANGELOG.md
          files: |
            **/out/_astrolabe
            **/out/_astrolabe.ps1
            **/out/astrolabe.bash
            **/out/astrolabe.elv
            **/out/astrolabe.fish
            **/out/astrolabe.1

  build-binaries:
    name: Compile for ${{ matrix.platform.platform_name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-i686
            runs-on: ubuntu-22.04
            target: i686-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc

          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: "--bin astrolabe --locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: astrolabe
          target: ${{ matrix.platform.target }}
