name: Unit Tests

on:
  push:
    branches:
      - dev
      - master
      - "release-candidate/**"
  pull_request:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest:
            os-flags: "-- --skip ui --exact"
          - ubuntu-latest:
            os-flags: ""
        flags: [--no-default-features, --all-features]
    name: Test suite
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test ${{ matrix.flags }} ${{ matrix.os-flags }}
