name: Unit Tests

on:
  push:
    branches:
      - dev
      - master
      - "release-candidate/**"
    paths:
      - wasm/**
  pull_request:
    paths:
      - wasm/**

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  targets:
    name: Test suite (wasm)
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu]
        toolchain: [stable]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
          targets: wasm32-unknown-unknown
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: cargo test -p astrograph-wasm
        if: matrix.os == 'ubuntu'
      - run: cargo test -p astrograph-wasm -- --skip ui --exact
        if: matrix.os == 'windows'
      - run: wasm-pack test --firefox --headless wasm

  deep_check:
    name: Clippy Check (wasm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.29.5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, fmt
      - name: Run rust fmt
        run: cargo fmt -p astrograph-wasm --check
      - name: Run Clippy (Pedantic)
        run: cargo clippy --all-targets -p astrograph-wasm -- -D clippy::pedantic
      #- name: Run miri
      #  run: cargo miri setup
      #- run: MIRIFLAGS=-Zmiri-disable-isolation cargo miri test
      #  env:
      #    MIRIFLAGS: -Zmiri-strict-provenance
